name: Devops class strat git hub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # or your exact runner label from `./config.sh`
    steps:
      - name: print hello world
        run: |
          echo "hello world"
          hostname
          ip a
          cd /var/www/html
          git pull origin main
